config/routes.rb
Rails.application.routes.draw do

  resources :enrollments

  resources :products
  get 'shop/index'

  resources :locations
  resources :places
  get 'search', :to=> 'activities#search'
  get 'home/about'

  controller :sessions do
	get 'login' => :newCus
	post 'login' => :createCus
	get 'logout' => :destroyCus
	delete 'logout' => :destroyCus
	get 'secondlogin' => :newEmp
	post 'secondlogin' => :createEmp
	get 'secondlogout' => :destroyEmp
	delete 'secondlogout' => :destroyEmp
  end  
  resources :activities do
	resources :enrollments
  end
  resources :rooms
  resources :memberships
  resources :instructors
  resources :equipment
  resources :customers
  resources :sessions
  resources :pages

  root :to => 'pages#home'
  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :instructor
	belongs_to :room
	has_many :enrollments
	self.inheritance_column = nil
	validates :room_id, presence: true
	validates :instructor_id, presence: true
	validates :class_date, presence: true 
	validates :type, presence: true
	
	def self.search(search)
	where("type LIKE ?", "%#{search}%") 
	end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :memberships, dependent: :destroy
	validates :username, uniqueness: true
	validates :username, presence: true 
	validates :password, presence: true 
	validates :name, presence: true 
	validates :surname, presence: true 
	validates :password, confirmation: true
	validates :email, presence: true 
	validates :phone, numericality: { only_integer: true }
	validates :emergency_number, numericality: { only_integer: true }
	has_many :enrollments 
	has_secure_password
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
belongs_to :customer
belongs_to :activity
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	belongs_to :room
	validates :room_id, presence: true 
	validates :description, presence: true 
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
	has_many :activities, dependent: :destroy
	validates :username, uniqueness: true
	validates :username, presence: true 
	validates :password, presence: true 
	validates_uniqueness_of :username
	validates :password, confirmation: true
	has_secure_password
	belongs_to :instructor	
end

app/models/location.rb
class Location < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :customer
	validates :customer_id, presence: true 
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :equipment, dependent: :destroy
	self.inheritance_column = nil
	validates :type, presence: true 
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  before_action :set_membership, only: [:show, :edit, :update, :destroy]
  before_action :secondauthorise
  # GET /memberships
  # GET /memberships.json
  def index
    @memberships = Membership.all
  end

  # GET /memberships/1
  # GET /memberships/1.json
  def show
  end

  # GET /memberships/new
  def new
    @membership = Membership.new
  end

  # GET /memberships/1/edit
  def edit
  end

  # POST /memberships
  # POST /memberships.json
  def create
    @membership = Membership.new(membership_params)

    respond_to do |format|
      if @membership.save
        format.html { redirect_to @membership, notice: 'Membership was successfully created.' }
        format.json { render :show, status: :created, location: @membership }
      else
        format.html { render :new }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /memberships/1
  # PATCH/PUT /memberships/1.json
  def update
    respond_to do |format|
      if @membership.update(membership_params)
        format.html { redirect_to @membership, notice: 'Membership was successfully updated.' }
        format.json { render :show, status: :ok, location: @membership }
      else
        format.html { render :edit }
        format.json { render json: @membership.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /memberships/1
  # DELETE /memberships/1.json
  def destroy
    @membership.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Membership was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membership
      @membership = Membership.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def membership_params
      params.require(:membership).permit(:date_created, :expiry_date, :length, :price_paid, :customer_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def signed_in?
		if session[:customer_id].nil?
			return
		else
			@current_customer = Customer.find_by_id(session[:customer_id])
		end
	end
	
	def secondsigned_in?
		if session[:instructor_id].nil?
			return
		else
		@current_instructor = Instructor.find_by_id(session[:instructor_id])
 end
end
def age(dob)
  now = Time.now.utc.to_date
  now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
end
def euro(amount)
number_to_currency(amount, :unit => '€')
end
end

app/helpers/customers_helper.rb
module CustomersHelper

end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/memberships_helper.rb
module MembershipsHelper

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/memberships/_form.html.erb
<%= form_for(@membership) do |f| %>
  <% if @membership.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@membership.errors.count, "error") %> prohibited this membership from being saved:</h2>

      <ul>
      <% @membership.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :date_created %><br>
			</div>
    <div class="controls">
    <%= f.date_select :date_created%>
  </div>
  <div class="control-group">
    <%= f.label :expiry_date %><br>
			</div>
    <div class="controls">
    <%= f.date_select :expiry_date %>
  </div>
  <div class="control-group">
    <%= f.label :length %><br>
			</div>
    <div class="controls">
    <%= f.number_field :length %>
  </div>
  <div class="control-group">
    <%= f.label :price_paid %><br>
			</div>
    <div class="controls">
    <%= f.text_field :price_paid %>
  </div>
  <div class="control-group">
    <%= f.label :customer_id %><br>
			</div>
    <div class="controls">
    <%= f.collection_select :customer_id, Customer.all, :id, :surname %>
  </div>
  <p>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-info" %>
  </div>
<% end %>

app/views/memberships/edit.html.erb
<h1>Editing Membership</h1>

<%= render 'form' %>

<%= link_to 'Show', @membership %> |
<%= link_to 'Back', memberships_path %>

app/views/memberships/index.html.erb
<h1>Listing Memberships</h1>

<table class="table table-bordered">
  <thead>
    <tr>
	
      <th>Date created</th>
      <th>Expiry date</th>
      <th>Length (In Years)</th>
      <th>Price paid</th>
      <th>Customer</th>
    </tr>
  </thead>

  <tbody>
    <% @memberships.each do |membership| %>
      <tr>
        <td><%= membership.date_created %></td>
        <td><%= membership.expiry_date %></td>
        <td><%= membership.length %></td>
        <td><%= euro membership.price_paid %></td>
        <td><%= membership.customer.name %></td>
        <td><%= link_to 'Show', membership %>
        <%= link_to 'Edit', edit_membership_path(membership) %>
        <%= link_to 'Destroy', membership, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Membership', new_membership_path %>

app/views/memberships/new.html.erb
<h1>New Membership</h1>

<%= render 'form' %>

<%= link_to 'Back', memberships_path %>

app/views/memberships/show.html.erb
<dl class ="dl-horizontal">


  <dt><strong>Date created:</strong></dt>
 <dd> <%= @membership.date_created %></dd>



  <dt><strong>Expiry date:</strong></dt>
 <dd> <%= @membership.expiry_date %></dd>



 <dt> <strong>Length:</strong></dt>
 <dd> <%= @membership.length %></dd>



 <dt> <strong>Price paid:</strong></dt>
 <dd> <%= @membership.price_paid %></dd>



  <dt><strong>Customer:</strong></dt>
  <dd><%= @membership.customer_id %></dd>


<%= link_to 'Edit', edit_membership_path(@membership) %> |
<%= link_to 'Back', memberships_path %>