config/routes.rb
Rails.application.routes.draw do

  resources :enrollments

  resources :products
  get 'shop/index'

  resources :locations
  resources :places
  get 'search', :to=> 'activities#search'
  get 'home/about'

  controller :sessions do
	get 'login' => :newCus
	post 'login' => :createCus
	get 'logout' => :destroyCus
	delete 'logout' => :destroyCus
	get 'secondlogin' => :newEmp
	post 'secondlogin' => :createEmp
	get 'secondlogout' => :destroyEmp
	delete 'secondlogout' => :destroyEmp
  end  
  resources :activities do
	resources :enrollments
  end
  resources :rooms
  resources :memberships
  resources :instructors
  resources :equipment
  resources :customers
  resources :sessions
  resources :pages

  root :to => 'pages#home'
  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :instructor
	belongs_to :room
	has_many :enrollments
	self.inheritance_column = nil
	validates :room_id, presence: true
	validates :instructor_id, presence: true
	validates :class_date, presence: true 
	validates :type, presence: true
	
	def self.search(search)
	where("type LIKE ?", "%#{search}%") 
	end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :memberships, dependent: :destroy
	validates :username, uniqueness: true
	validates :username, presence: true 
	validates :password, presence: true 
	validates :name, presence: true 
	validates :surname, presence: true 
	validates :password, confirmation: true
	validates :email, presence: true 
	validates :phone, numericality: { only_integer: true }
	validates :emergency_number, numericality: { only_integer: true }
	has_many :enrollments 
	has_secure_password
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
belongs_to :customer
belongs_to :activity
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	belongs_to :room
	validates :room_id, presence: true 
	validates :description, presence: true 
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
	has_many :activities, dependent: :destroy
	validates :username, uniqueness: true
	validates :username, presence: true 
	validates :password, presence: true 
	validates_uniqueness_of :username
	validates :password, confirmation: true
	has_secure_password
	belongs_to :instructor	
end

app/models/location.rb
class Location < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :customer
	validates :customer_id, presence: true 
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :equipment, dependent: :destroy
	self.inheritance_column = nil
	validates :type, presence: true 
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :set_instructor, only: [:show, :edit, :update, :destroy]
  before_action :secondauthorise, only: [:show, :edit, :update, :destroy]
  # GET /instructors
  # GET /instructors.json
  def index
    @instructors = Instructor.all
  end

  # GET /instructors/1
  # GET /instructors/1.json
  def show
  end

  # GET /instructors/new
  def new
    @instructor = Instructor.new
  end

  # GET /instructors/1/edit
  def edit
  end

  # POST /instructors
  # POST /instructors.json
  def create
    @instructor = Instructor.new(instructor_params)

    respond_to do |format|
      if @instructor.save
        format.html { redirect_to @instructor, notice: 'Instructor was successfully created.' }
        format.json { render :show, status: :created, location: @instructor }
      else
        format.html { render :new }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /instructors/1
  # PATCH/PUT /instructors/1.json
  def update
    respond_to do |format|
      if @instructor.update(instructor_params)
        format.html { redirect_to @instructor, notice: 'Instructor was successfully updated.' }
        format.json { render :show, status: :ok, location: @instructor }
      else
        format.html { render :edit }
        format.json { render json: @instructor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /instructors/1
  # DELETE /instructors/1.json
  def destroy
    @instructor.destroy
    respond_to do |format|
      format.html { redirect_to instructors_url, notice: 'Instructor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_instructor
      @instructor = Instructor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def instructor_params
      params.require(:instructor).permit(:certification, :name, :surname, :date_of_birth, :PPS, :phone_number, :address, :manager, :username, :password, :password_confirmation, :image)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def signed_in?
		if session[:customer_id].nil?
			return
		else
			@current_customer = Customer.find_by_id(session[:customer_id])
		end
	end
	
	def secondsigned_in?
		if session[:instructor_id].nil?
			return
		else
		@current_instructor = Instructor.find_by_id(session[:instructor_id])
 end
end
def age(dob)
  now = Time.now.utc.to_date
  now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
end
def euro(amount)
number_to_currency(amount, :unit => '€')
end
end

app/helpers/customers_helper.rb
module CustomersHelper

end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/instructors/_form.html.erb
<%= form_for(@instructor) do |f| %>
  <% if @instructor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :certification %><br>
		</div>
    <div class="controls">
    <%= f.text_field :certification %>
  </div>
  <div class="control-group">
    <%= f.label :name %><br>
		</div>
    <div class="controls">
    <%= f.text_field :name %>
  </div>
  <div class="control-group">
    <%= f.label :surname %><br>
		</div>
  <div class="control-group">
    <%= f.text_field :surname %>
  </div>
  <div class="control-group">
    <%= f.label :date_of_birth %><br>
		</div>
    <div class="controls">
    <%= f.date_select :date_of_birth, :start_year => 1950, :end_year => Time.now.year-18 %>
  </div>
  <div class="control-group">
    <%= f.label :PPS %><br>
		</div>
    <div class="controls">
    <%= f.text_field :PPS %>
  </div>
  <div class="control-group">
    <%= f.label :phone_number %><br>
		</div>
    <div class="controls">
    <%= f.text_field :phone_number %>
  </div>
   <div class="control-group">
    <%= f.label :address %><br>
		</div>
    <div class="controls">
	<%= f.text_field :address %>
  </div>
  <div class="control-group">
    <%= f.label :manager %><br>
		</div>
    <div class="controls">
    <%= f.collection_select :manager, Instructor.all, :id, :name %>
  </div>
  <div class="control-group">
    <%= f.label :username %><br>
		</div>
    <div class="controls">
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
		</div>
    <div class="controls">
    <%= f.password_field :password %>
  </div>
  <div class="field">
	<%= f.label :password_confirmation %><br />
		</div>
    <div class="controls">
	<%= f.password_field :password_confirmation %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
		</div>
    <div class="controls">
    <%= f.text_field :image %>
	<p>
  </div>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-info" %>
  </div>
<% end %>

app/views/instructors/edit.html.erb
<h1>Editing Instructor</h1>

<%= render 'form' %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<h1>Listing Instructors</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Certification</th>
      <th>Name</th>
      <th>Surname</th>
      <th>Age</th>
      <th>Phone number</th>
      <th>Address</th>
      <th>Username</th>
      <th>Image</th>
    </tr>
  </thead>

  <tbody>
    <% @instructors.each do |instructor| %>
      <tr>
        <td><%= instructor.certification %></td>
        <td><%= instructor.name %></td>
        <td><%= instructor.surname %></td>
        <td><%= age instructor.date_of_birth %></td>
        <td><%= instructor.phone_number %></td>
        <td><%= instructor.address %></td>
        <td><%= instructor.username %></td>
        <td><%= link_to image_tag(instructor.image, size:"150x100") %></td>
        <td><%= link_to 'Show', instructor %>
        <%= link_to 'Edit', edit_instructor_path(instructor) %>
        <%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>New Instructor</h1>

<%= render 'form' %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<dl class ="dl-horizontal">
  <dt><strong>Certification:</strong></dt>
 <dd><%= @instructor.certification %></dd>



  <dt><strong>Name:</strong></dt>
  <dd><%= @instructor.name %></dd>



  <dt><strong>Surname:</strong></dt>
  <dd><%= @instructor.surname %></dd>



  <dt><strong>Date of birth:</strong></dt>
  <dd><%= @instructor.date_of_birth %></dd>



  <dt><strong>Pps:</strong></dt>
  <dd><%= @instructor.PPS %></dd>



  <dt><strong>Phone number:</strong></dt>
  <dd><%= @instructor.phone_number %></dd>



  <dt><strong>Address:</strong></dt>
  <dd><%= @instructor.address %></dd>



  <dt><strong>Username:</strong></dt>
  <dd><%= @instructor.username %></dd>



  <dt><strong>Password:</strong></dt>
  <dd><%= @instructor.password %></dd>



  <dt><strong>Image:</strong></dt>
  <dd><%= link_to image_tag(@instructor.image, size:"150x100") %></dd>


<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>