config/routes.rb
Rails.application.routes.draw do

  resources :enrollments

  resources :products
  get 'shop/index'

  resources :locations
  resources :places
  get 'search', :to=> 'activities#search'
  get 'home/about'

  controller :sessions do
	get 'login' => :newCus
	post 'login' => :createCus
	get 'logout' => :destroyCus
	delete 'logout' => :destroyCus
	get 'secondlogin' => :newEmp
	post 'secondlogin' => :createEmp
	get 'secondlogout' => :destroyEmp
	delete 'secondlogout' => :destroyEmp
  end  
  resources :activities do
	resources :enrollments
  end
  resources :rooms
  resources :memberships
  resources :instructors
  resources :equipment
  resources :customers
  resources :sessions
  resources :pages

  root :to => 'pages#home'
  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
	belongs_to :instructor
	belongs_to :room
	has_many :enrollments
	self.inheritance_column = nil
	validates :room_id, presence: true
	validates :instructor_id, presence: true
	validates :class_date, presence: true 
	validates :type, presence: true
	
	def self.search(search)
	where("type LIKE ?", "%#{search}%") 
	end
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_many :memberships, dependent: :destroy
	validates :username, uniqueness: true
	validates :username, presence: true 
	validates :password, presence: true 
	validates :name, presence: true 
	validates :surname, presence: true 
	validates :password, confirmation: true
	validates :email, presence: true 
	validates :phone, numericality: { only_integer: true }
	validates :emergency_number, numericality: { only_integer: true }
	has_many :enrollments 
	has_secure_password
end

app/models/enrollment.rb
class Enrollment < ActiveRecord::Base
belongs_to :customer
belongs_to :activity
end

app/models/equipment.rb
class Equipment < ActiveRecord::Base
	belongs_to :room
	validates :room_id, presence: true 
	validates :description, presence: true 
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
	has_many :activities, dependent: :destroy
	validates :username, uniqueness: true
	validates :username, presence: true 
	validates :password, presence: true 
	validates_uniqueness_of :username
	validates :password, confirmation: true
	has_secure_password
	belongs_to :instructor	
end

app/models/location.rb
class Location < ActiveRecord::Base
	geocoded_by :address
	after_validation :geocode
end

app/models/membership.rb
class Membership < ActiveRecord::Base
	belongs_to :customer
	validates :customer_id, presence: true 
end

app/models/place.rb
class Place < ActiveRecord::Base
end

app/models/room.rb
class Room < ActiveRecord::Base
	has_many :equipment, dependent: :destroy
	self.inheritance_column = nil
	validates :type, presence: true 
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_action :secondauthorise, only: [:new, :edit, :update, :destroy]
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end 
  
  def search
	@activities = Activity.search params[:query]
	unless @activities.empty? #if !@modelnames.empty?
	render 'index' #will only show records matching the search
	else
	flash[:notice] = 'No record matches that search'
	render 'index' #will show all records
	end
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:type, :class_date, :size, :duration, :room_id, :instructor_id)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def signed_in?
		if session[:customer_id].nil?
			return
		else
			@current_customer = Customer.find_by_id(session[:customer_id])
		end
	end
	
	def secondsigned_in?
		if session[:instructor_id].nil?
			return
		else
		@current_instructor = Instructor.find_by_id(session[:instructor_id])
 end
end
def age(dob)
  now = Time.now.utc.to_date
  now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
end
def euro(amount)
number_to_currency(amount, :unit => '€')
end
end

app/helpers/customers_helper.rb
module CustomersHelper

end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/equipment_helper.rb
module EquipmentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :type, :class => "control-label" %><br>
	</div>
    <div class="controls">
	<%= f.text_field :type, placeholder: "Describe the Class" %>
  </div>
  <div class="control-group">
    <%= f.label :class_date, :class => "control-label" %><br>
	</div> 
	<div class = "controls">
    <%= f.date_select :class_date %>
  </div>
  <div class="control-group">
    <%= f.label :size, :class => "control-label" %><br>
	</div>
	<div class ="controls">
    <%= f.number_field :size, placeholder: "Maximum Size" %>
  </div>
  <div class="control-group">
    <%= f.label :duration, :class => "control-label"  %><br>
	</div>
	<div class = "controls"> 
    <%= f.number_field :duration, placeholder: "In Minutes" %>
  </div>
  <div class="control-group">
    <%= f.label :room_id, :class => "control-label"  %><br>
	</div>
	<div class = controls>
	<%= f.collection_select :room_id, Room.all, :id, :type %>
  </div>
  <div class="control-group">
    <%= f.label :instructor_id, :class => "control-label"  %><br>
	</div>
	<div class = "controls">
	<%= f.collection_select :instructor_id, Instructor.all, :id, :name %>
  </div>
  <p>
  <div class="actions">
    <%= f.submit "Submit", :class => "btn btn-info"%>
  </div>
<% end %>

app/views/activities/_search.html.erb
<%= form_tag(search_path, method: :get) do %>
	<%= text_field_tag(:query, params[:query], placeholder: "Search Classes") %> 
	<%= submit_tag "Search Classes" %>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing Activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Classes</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Type</th>
      <th>Class date</th>
      <th>Size</th>
      <th>Duration</th>
      <th>Room</th>
      <th>Instructor</th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= activity.type %></td>
        <td><%= activity.class_date %></td>
        <td><%= activity.size %></td>
        <td><%= activity.duration %> Minutes</td>
        <td><%= activity.room.type %></td>
        <td><%= activity.instructor.name %></td>
        <td><%= link_to 'Show', activity %>
		<% if signed_in? %>
		<%= link_to 'Enroll Now', enrollments_path(@enrollment, enrollment: {user_id: @current_customer.id, lecture_id: activity.id}), :method => :post %>
		<% end %>
		<% if secondsigned_in? %>
        <%= link_to 'Edit', edit_activity_path(activity) %>
        <%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% end %>
	  </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if secondsigned_in? %>
<%= link_to 'New Activity', new_activity_path %>
<% end %> 

app/views/activities/new.html.erb
<h1>New Activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<dl class ="dl-horizontal">
  <dt>Type:</dt>
  <dd><%= @activity.type %></dd>

  <dt>Class date:</strong></dt>
  <dd><%= @activity.class_date %></dd>


  <dt><strong>Size:</strong></dt>
  <dd><%= @activity.size %></dd>


  <dt><strong>Duration:</strong></dt>
  <dd><%= @activity.duration %></dd>


  <dt><strong>Room:</strong></dt>
  <dd><%= @activity.room_id %></dd>


  <dt><strong>Instructor:</strong></dt>
  <dd><%= @activity.instructor.name %></dd>
</div>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>